# Generated by Django 6.0.6 on 2026-07-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClubTeam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Point',
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='goal_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goals_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goals_for',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='standing',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
