# Generated by Django 6.0.6 on 2026-07-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClubTeam', '0002_remove_match_match_date_remove_team_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.AddField(
            model_name='player',
            name='Allgoals',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='playermatchscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_in_match', models.PositiveIntegerField(default=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='myClubTeam.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='myClubTeam.player')),
            ],
        ),
    ]
