# Generated by Django 6.0.6 on 2026-07-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClubTeam', '0003_remove_player_goals_player_allgoals_playermatchscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchscore',
            name='min_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
