# Generated by Django 6.0.6 on 2026-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClubTeam', '0004_playermatchscore_min_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchscore',
            name='min_goal',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
