# Generated by Django 6.0.6 on 2026-07-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClubTeam', '0005_alter_playermatchscore_min_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchscore',
            name='min_goal',
        ),
        migrations.AlterField(
            model_name='playermatchscore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Matchgoals', to='myClubTeam.match'),
        ),
        migrations.AlterField(
            model_name='playermatchscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Playergoals', to='myClubTeam.player'),
        ),
    ]
