# Generated by Django 6.0.6 on 2026-07-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClubTeam', '0006_remove_playermatchscore_min_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchscore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='myClubTeam.match'),
        ),
    ]
