# Generated by Django 6.0.6 on 2026-07-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClubTeam', '0007_alter_playermatchscore_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='myClubTeam.player'),
        ),
    ]
