# Generated by Django 6.0.6 on 2026-07-20 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myClubTeam', '0008_alter_playermatchscore_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchscore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchgoals', to='myClubTeam.match'),
        ),
        migrations.AlterField(
            model_name='playermatchscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playergoals', to='myClubTeam.player'),
        ),
    ]
